export const collectionData = [
   {
      id: 1,
      category: "multidaytrip",
      title: "Garden of Eden",
      thumbImg: "/src/assets/images/private-tours/get-inspired/1.jpg",
      ratingStars: 5,
      ratingCount: 2350,
      depart: "Barahona",
      descriptionTitle: "Eco-Adventure: Fruitful Fruits",
      description:
         "Discover the enchanting flavors of the Caribbean in this unique eco-adventure, where you'll taste the freshest fruits from local farms. Relax on lush terraces while enjoying guided tours of the vibrant gardens and learning about the rich biodiversity of the region.",
      price: 100,
   },
   {
      id: 2,
      category: "privatetour",
      title: "Horseback Riding",
      thumbImg: "/src/assets/images/private-tours/get-inspired/2.jpg",
      ratingStars: 5,
      ratingCount: 1399,
      depart: "Haiti",
      descriptionTitle: "Journey to Haiti: A Riding Odyssey",
      description:
         "Step into the heart of Haiti and experience the thrill of riding horses through the lush countryside. Join a guided tour to explore the ancient ruins, learn about local culture, and immerse yourself in the breathtaking scenery.",
      price: 97,
   },
   {
      id: 3,
      category: "privatetour",
      title: "Blue Jewel Mine",
      thumbImg: "/src/assets/images/private-tours/get-inspired/4.jpg",
      ratingStars: 4,
      ratingCount: 4389,
      depart: "Dominican Republic",
      descriptionTitle: "Mining Adventure: A Hidden Treasure",
      description:
         "Discover the hidden treasures of the Dominican Republic with this unique eco-adventure, where you'll visit the Blue Jewel Mine. Learn about the mining history, explore the beautiful mineral-rich landscape, and enjoy guided tours of the surrounding villages.",
      price: 128,
   },
   {
      id: 4,
      category: "multidaytrip",
      title: "Untouched Paradise",
      thumbImg: "/src/assets/images/private-tours/get-inspired/4.jpg",
      ratingStars: 4,
      ratingCount: 349,
      depart: "Barahona",
      descriptionTitle: "Escape the Crowds: A Barahona Escape",
      description:
         "Escape the crowds and immerse yourself in the untouched beauty of Barahona's natural wonders. Join a guided tour to explore the pristine beaches, lush rainforests, and learn about the rich biodiversity of the region.",
      price: 147,
   },
   {
      id: 5,
      category: "multidaytrip",
      title: "Cloud Forest Mountain",
      thumbImg: "/src/assets/images/private-tours/get-inspired/6.jpg",
      ratingStars: 5,
      ratingCount: 4370,
      depart: "Barahona",
      descriptionTitle: "Natural Wonders: The Sky's Edge",
      description:
         "Ascend to the majestic Cloud Forest Mountain in Barahona and experience the awe-inspiring views of the surrounding landscape. Join a guided tour to learn about the unique flora and fauna, and immerse yourself in the tranquility of this pristine mountain.",
      price: 97,
   },
   {
      id: 6,
      category: "daytrip",
      title: "Whale Watching",
      thumbImg: "/src/assets/images/destinations/destination-3.jpg",
      ratingStars: 4,
      ratingCount: 2700,
      depart: "Haiti",
      descriptionTitle: "Marine Miracle: A Whale Watching Adventure",
      description:
         "Discover the enchanting beauty of the Caribbean Sea in this unique eco-adventure, where you'll witness the majestic whales up close. Join a guided tour to explore the beautiful coral reefs, learn about local marine life, and immerse yourself in the breathtaking scenery.",
      price: 125,
   },
   {
      id: 7,
      category: "privatetour",
      title: "Wildlife Sanctuary",
      thumbImg: "/src/assets/images/destinations/destination-3.jpg",
      ratingStars: 4,
      ratingCount: 2292,
      depart: "Barahona",
      descriptionTitle: "A Hidden Paradise: The Wildlife Sanctuary",
      description:
         "Escape the crowds and immerse yourself in the untouched beauty of the Wildlife Sanctuary in Barahona. Join a guided tour to explore the pristine beaches, lush rainforests, and learn about the rich biodiversity of the region.",
      price: 114,
   },
   {
      id: 8,
      category: "privatetour",
      title: "Adventure Awaits",
      thumbImg: "/src/assets/images/private-tours/get-inspired/1.jpg",
      ratingStars: 4,
      ratingCount: 2754,
      depart: "Barahona",
      descriptionTitle: "The Hidden Valley: A Journey of Discovery",
      description:
         "Step into the heart of the Caribbean and embark on a unique eco-adventure, where you'll discover the hidden valleys and their enchanting landscapes. Join a guided tour to learn about the unique flora and fauna, and immerse yourself in the breathtaking scenery.",
      price: 104,
   },
   {
      id: 9,
      category: "multidaytrip",
      title: "Breathtaking Beaches",
      thumbImg: "/src/assets/images/destinations/destination-3.jpg",
      ratingStars: 5,
      ratingCount: 794,
      depart: "Barahona",
      descriptionTitle: "A Sandy Paradise: The Breathtaking Beaches",
      description:
         "Escape the crowds and immerse yourself in the untouched beauty of the Barahona beaches. Join a guided tour to explore the pristine beaches, lush rainforests, and learn about the rich biodiversity of the region.",
      price: 96,
   },
   {
      id: 10,
      category: "multidaytrip",
      title: "Aerial Adventure",
      thumbImg: "/src/assets/images/private-tours/get-inspired/4.jpg",
      ratingStars: 5,
      ratingCount: 129,
      depart: "Barahona",
      descriptionTitle: "The Sky's Edge: Aerial Adventure on Barahona",
      description:
         "Ascend to the majestic Barahona in search of the awe-inspiring views of the surrounding landscape. Join a guided tour to learn about the unique flora and fauna, and immerse yourself in the tranquility of this pristine mountain.",
      price: 80,
   },
   {
      id: 11,
      category: "multidaytrip",
      title: "Island Paradise",
      thumbImg: "/src/assets/images/private-tours/get-inspired/6.jpg",
      ratingStars: 4,
      ratingCount: 129,
      depart: "Haiti",
      descriptionTitle:
         "Escape the crowds and immerse yourself in the untouched beauty of the Haitian islands.",
      description:
         "Join a guided tour to explore the pristine beaches, lush rainforests, and learn about the rich biodiversity of the region.",
      price: 135,
   },
   {
      id: 12,
      category: "multidaytrip",
      title: "Cultural Immersion",
      thumbImg: "/src/assets/images/destinations/destination-1.jpg",
      ratingStars: 4,
      ratingCount: 110,
      depart: "Dominican Republic",
      descriptionTitle:
         "Discover the rich history and unique culture of the Dominican Republic with this unique eco-adventure.",
      description:
         "Join a guided tour to explore the ancient ruins, learn about local traditions, and immerse yourself in the breathtaking scenery.",
      price: 110,
   },
   {
      id: 13,
      category: "multidaytrip",
      title: "Natural Wonders",
      thumbImg: "/src/assets/images/private-tours/get-inspired/1.jpg",
      ratingStars: 5,
      ratingCount: 140,
      depart: "Barahona",
      descriptionTitle:
         "Escape the crowds and immerse yourself in the untouched beauty of Barahona's natural wonders.",
      description:
         "Join a guided tour to explore the pristine beaches, lush rainforests, and learn about the rich biodiversity of the region.",
      price: 140,
   },
   {
      id: 14,
      category: "daytrip",
      title: "Waterfall Adventure",
      thumbImg: "/src/assets/images/destinations/destination-3.jpg",
      ratingStars: 5,
      ratingCount: 105,
      depart: "Haiti",
      descriptionTitle:
         "Step into the heart of Haiti and experience the thrill of riding horses through the lush countryside.",
      description:
         "Join a guided tour to explore the ancient ruins, learn about local culture, and immerse yourself in the breathtaking scenery.",
      price: 105,
   },
   {
      id: 15,
      category: "privatetour",
      title: "Mining Miracle",
      thumbImg: "/src/assets/images/destinations/destination-3.jpg",
      ratingStars: 5,
      ratingCount: 130,
      depart: "Dominican Republic",
      descriptionTitle:
         "Discover the hidden treasures of the Dominican Republic with this unique eco-adventure, where you'll visit the Blue Jewel Mine.",
      description:
         "Learn about the mining history, explore the beautiful mineral-rich landscape, and enjoy guided tours of the surrounding villages.",
      price: 130,
   },
   {
      id: 16,
      category: "daytrip",
      title: "Cultural Odyssey",
      thumbImg: "/src/assets/images/destinations/destination-1.jpg",
      ratingStars: 5,
      ratingCount: 150,
      depart: "Haiti",
      descriptionTitle: "A Journey Through Time: A Cultural Odyssey",
      description:
         "Discover the rich history and unique culture of Haiti in this unique eco-adventure. Join a guided tour to explore the ancient ruins, learn about local traditions, and immerse yourself in the breathtaking scenery.",
      price: 115,
   },
   {
      id: 17,
      category: "multidaytrip",
      title: "Hidden Gems",
      thumbImg: "/src/assets/images/destinations/destination-1.jpg",
      ratingStars: 4,
      ratingCount: 120,
      depart: "Barahona",
      descriptionTitle: "A Journey to the Undiscovered: Hidden Gems",
      description:
         "Discover the enchanting beauty of Barahona's lesser-known attractions in this unique eco-adventure. Join a guided tour to explore the hidden beaches, lush rainforests, and learn about the rich biodiversity of the region.",
      price: 100,
   },
   {
      id: 18,
      category: "privatetour",
      title: "Marine Life Adventure",
      thumbImg: "/src/assets/images/destinations/destination-3.jpg",
      ratingStars: 5,
      ratingCount: 250,
      depart: "Haiti",
      descriptionTitle: "A Marine Life Adventure: A Whale Watching Odyssey",
      description:
         "Discover the enchanting beauty of the Caribbean Sea in this unique eco-adventure, where you'll witness the majestic whales up close. Join a guided tour to explore the beautiful coral reefs, learn about local marine life, and immerse yourself in the breathtaking scenery.",
      price: 125,
   },
   {
      id: 19,
      category: "mutlidaytrip",
      title: "Aerial Exploration",
      thumbImg: "/src/assets/images/destinations/destination-1.jpg",
      ratingStars: 4,
      ratingCount: 100,
      depart: "Dominican Republic",
      descriptionTitle: "Aerial Adventure: The Sky's Edge",
      description:
         "Ascend to the majestic Dominican Republic in search of the awe-inspiring views of the surrounding landscape. Join a guided tour to learn about the unique flora and fauna, and immerse yourself in the tranquility of this pristine mountain.",
      price: 80,
   },
   {
      id: 20,
      category: "daytrip",
      title: "Uncharted Waters",
      thumbImg: "/src/assets/images/destinations/destination-3.jpg",
      ratingStars: 5,
      ratingCount: 75,
      depart: "Haiti",
      descriptionTitle: "A Journey to the Undiscovered: Uncharted Waters",
      description:
         "Discover the enchanting beauty of Haiti's lesser-known attractions in this unique eco-adventure. Join a guided tour to explore the hidden beaches, lush rainforests, and learn about the rich biodiversity of the region.",
      price: 95,
   },
];
